version: "3.7"
services: 

  frontend:
    build: ./frontend
    ports:
      - "80:4200"

  backend:
    build: ./backend
    ports: 
      - "5000:5000"

  redis:
    image: redis:6.0.1-alpine
  